[Params.Sidebar]
emoji = 'ğŸ¡'
avatar = { enabled = true, local = true, src = 'img/avatar.jpeg' }
subtitle = 'consistency'

[Params.Footer]
customText = 'Maintained with ğŸ¤'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
    identifier = 'Home'